<?php

namespace Database\Seeders;

use App\Models\WordBankEntry;
use App\Models\WordBankGroup;
use Illuminate\Database\Seeder;

class WordBankSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        foreach ($this->groups() as $groupIndex => $group) {
            $wordBankGroup = WordBankGroup::create([
                'name' => $group['name'],
                'order' => $groupIndex + 1,
            ]);

            foreach ($group['entries'] as $entryIndex => $entry) {
                WordBankEntry::create([
                    'word_bank_group_id' => $wordBankGroup->id,
                    'term' => $entry[0],
                    'native_language' => 'hi',
                    'native_meaning' => $entry[1],
                    'native_transliteration' => $entry[2],
                    'example_sentence' => $entry[3],
                    'order' => $entryIndex + 1,
                ]);
            }
        }
    }

    /**
     * 20 thematic groups of 25 words each (500 total), levelled for a Hindi-speaking
     * beginner-to-intermediate learner. Each entry is [term, native_meaning (Devanagari),
     * native_transliteration (romanized), example_sentence].
     *
     * @return list<array{name: string, entries: list<array{0: string, 1: string, 2: string, 3: string}>}>
     */
    private function groups(): array
    {
        return [
            [
                'name' => 'Greetings & Politeness',
                'entries' => [
                    ['hello', 'नमस्ते', 'namaste', 'Hello, how are you?'],
                    ['good morning', 'सुप्रभात', 'suprabhat', 'Good morning, sir.'],
                    ['good afternoon', 'शुभ दोपहर', 'shubh dopahar', 'Good afternoon, everyone.'],
                    ['good evening', 'शुभ संध्या', 'shubh sandhya', "Good evening, ma'am."],
                    ['good night', 'शुभ रात्रि', 'shubh raatri', 'Good night, sleep well.'],
                    ['please', 'कृपया', 'kripya', 'Please sit down.'],
                    ['thank you', 'धन्यवाद', 'dhanyavad', 'Thank you for your help.'],
                    ['thanks a lot', 'बहुत धन्यवाद', 'bahut dhanyavad', 'Thanks a lot for calling back.'],
                    ['sorry', 'माफ़ कीजिए', 'maaf kijiye', 'Sorry, I am five minutes late.'],
                    ['excuse me', 'सुनिए', 'suniye', 'Excuse me, where is the bus stop?'],
                    ["you're welcome", 'आपका स्वागत है', 'aapka swagat hai', "You're welcome, anytime."],
                    ['no problem', 'कोई बात नहीं', 'koi baat nahin', 'No problem, I can wait.'],
                    ['how are you', 'आप कैसे हैं', 'aap kaise hain', 'How are you today?'],
                    ['I am fine', 'मैं ठीक हूँ', 'main theek hoon', 'I am fine, thank you.'],
                    ['nice to meet you', 'आपसे मिलकर खुशी हुई', 'aapse milkar khushi hui', 'Nice to meet you, sir.'],
                    ['see you', 'फिर मिलेंगे', 'phir milenge', 'See you tomorrow.'],
                    ['goodbye', 'अलविदा', 'alvida', 'Goodbye, take care.'],
                    ['take care', 'ख्याल रखना', 'khyal rakhna', 'Take care, see you soon.'],
                    ['welcome', 'स्वागत है', 'swagat hai', 'Welcome to our home.'],
                    ['may I', 'क्या मैं', 'kya main', 'May I come in?'],
                    ['kindly', 'कृपया', 'kripya', 'Kindly check your email.'],
                    ['pardon', 'क्षमा करें', 'kshama karen', 'Pardon? Can you repeat that?'],
                    ['of course', 'बिल्कुल', 'bilkul', 'Of course, I will help you.'],
                    ['congratulations', 'बधाई हो', 'badhai ho', 'Congratulations on your new job.'],
                    ['all the best', 'शुभकामनाएँ', 'shubhkaamnaayen', 'All the best for your exam.'],
                ],
            ],
            [
                'name' => 'Numbers',
                'entries' => [
                    ['one', 'एक', 'ek', 'I have one brother.'],
                    ['two', 'दो', 'do', 'She has two children.'],
                    ['three', 'तीन', 'teen', 'There are three chairs here.'],
                    ['four', 'चार', 'chaar', "The meeting is at four o'clock."],
                    ['five', 'पाँच', 'paanch', 'I need five minutes, please.'],
                    ['six', 'छह', 'chhah', 'We start work at six.'],
                    ['seven', 'सात', 'saat', 'There are seven days in a week.'],
                    ['eight', 'आठ', 'aath', 'My shift starts at eight.'],
                    ['nine', 'नौ', 'nau', 'The shop opens at nine.'],
                    ['ten', 'दस', 'das', 'This costs ten rupees.'],
                    ['twenty', 'बीस', 'bees', 'I am twenty-nine years old.'],
                    ['thirty', 'तीस', 'tees', 'It will take thirty minutes.'],
                    ['forty', 'चालीस', 'chaalees', 'There are forty orders today.'],
                    ['fifty', 'पचास', 'pachaas', 'Give me fifty rupees, please.'],
                    ['hundred', 'सौ', 'sau', 'This bag costs one hundred rupees.'],
                    ['thousand', 'हज़ार', 'hazaar', 'The salary is fifteen thousand rupees.'],
                    ['first', 'पहला', 'pahla', 'This is my first day at work.'],
                    ['second', 'दूसरा', 'doosra', 'Take the second file from the top.'],
                    ['third', 'तीसरा', 'teesra', 'Our flat is on the third floor.'],
                    ['last', 'आख़िरी', 'aakhri', 'This is the last order for today.'],
                    ['half', 'आधा', 'aadha', 'I finished half of the work.'],
                    ['quarter', 'चौथाई', 'chauthai', 'It is a quarter past nine.'],
                    ['pair', 'जोड़ा', 'jodaa', 'She bought a pair of shoes.'],
                    ['dozen', 'दर्जन', 'darjan', 'We packed a dozen boxes.'],
                    ['zero', 'शून्य', 'shoonya', 'The stock count is zero today.'],
                ],
            ],
            [
                'name' => 'Time, Days & Months',
                'entries' => [
                    ['today', 'आज', 'aaj', 'I am learning English today.'],
                    ['tomorrow', 'कल', 'kal', 'I will call you tomorrow.'],
                    ['yesterday', 'कल', 'kal', 'I read a story yesterday.'],
                    ['now', 'अभी', 'abhi', 'I am busy right now.'],
                    ['later', 'बाद में', 'baad mein', 'Can we talk later?'],
                    ['morning', 'सुबह', 'subah', 'I study every morning.'],
                    ['afternoon', 'दोपहर', 'dopahar', 'We have lunch in the afternoon.'],
                    ['evening', 'शाम', 'shaam', 'I practise speaking in the evening.'],
                    ['night', 'रात', 'raat', 'I sleep early at night.'],
                    ['week', 'सप्ताह', 'saptaah', 'I study English every week.'],
                    ['month', 'महीना', 'mahina', 'This is my first month here.'],
                    ['year', 'साल', 'saal', 'I finished my degree last year.'],
                    ['Monday', 'सोमवार', 'somvaar', 'The market is closed on Monday.'],
                    ['Friday', 'शुक्रवार', 'shukravaar', 'We get paid on Friday.'],
                    ['Sunday', 'रविवार', 'ravivaar', 'Sunday is a holiday.'],
                    ['January', 'जनवरी', 'janvari', 'My birthday is in January.'],
                    ['date', 'तारीख़', 'taareekh', "What is today's date?"],
                    ['birthday', 'जन्मदिन', 'janamdin', 'Her birthday is next week.'],
                    ["o'clock", 'बजे', 'baje', "It is five o'clock."],
                    ['minute', 'मिनट', 'minat', 'Please wait one minute.'],
                    ['hour', 'घंटा', 'ghanta', 'I study for one hour daily.'],
                    ['early', 'जल्दी', 'jaldi', 'I woke up early today.'],
                    ['late', 'देर से', 'der se', "Please don't come late."],
                    ['always', 'हमेशा', 'hamesha', 'I always check my email.'],
                    ['never', 'कभी नहीं', 'kabhi nahin', 'I never miss my practice.'],
                ],
            ],
            [
                'name' => 'Family & People',
                'entries' => [
                    ['mother', 'माँ', 'maa', 'This is my mother.'],
                    ['father', 'पिता', 'pita', 'My father works in a shop.'],
                    ['sister', 'बहन', 'behan', 'I have one sister.'],
                    ['brother', 'भाई', 'bhai', 'My brother lives in Delhi.'],
                    ['parents', 'माता-पिता', 'mata-pita', 'My parents live nearby.'],
                    ['sibling', 'भाई-बहन', 'bhai-behan', 'I have one sibling.'],
                    ['son', 'बेटा', 'beta', 'Her son goes to school.'],
                    ['daughter', 'बेटी', 'beti', 'My daughter is very smart.'],
                    ['grandmother', 'दादी / नानी', 'dadi / nani', 'My grandmother tells nice stories.'],
                    ['grandfather', 'दादा / नाना', 'dada / nana', 'My grandfather is eighty years old.'],
                    ['uncle', 'चाचा / मामा', 'chacha / mama', 'My uncle lives near us.'],
                    ['aunt', 'चाची / मौसी', 'chachi / mausi', 'My aunt visited us last week.'],
                    ['cousin', 'चचेरा भाई / बहन', 'chachera bhai/behan', 'My cousin lives in Delhi.'],
                    ['friend', 'दोस्त', 'dost', 'She is my best friend.'],
                    ['neighbour', 'पड़ोसी', 'padosi', 'Our neighbour is very kind.'],
                    ['child', 'बच्चा', 'bachcha', 'The child is playing outside.'],
                    ['baby', 'शिशु', 'shishu', 'The baby is sleeping now.'],
                    ['people', 'लोग', 'log', 'Many people live in this colony.'],
                    ['man', 'आदमी', 'aadmi', 'That man is our neighbour.'],
                    ['woman', 'औरत', 'aurat', 'The woman at the desk helped me.'],
                    ['boy', 'लड़का', 'ladka', 'The boy is doing his homework.'],
                    ['girl', 'लड़की', 'ladki', 'The girl answered the phone politely.'],
                    ['elder', 'बड़ा', 'bada', 'Listen to your elders.'],
                    ['younger', 'छोटा', 'chhota', 'My younger brother is in college.'],
                    ['guest', 'मेहमान', 'mehmaan', 'We have a guest today.'],
                ],
            ],
            [
                'name' => 'Common Verbs 1',
                'entries' => [
                    ['eat', 'खाना', 'khaana', 'I eat breakfast at eight.'],
                    ['drink', 'पीना', 'peena', 'Please drink some water.'],
                    ['sleep', 'सोना', 'sona', 'I sleep by ten at night.'],
                    ['wake up', 'जागना', 'jaagna', 'I wake up at six.'],
                    ['go', 'जाना', 'jaana', 'I go to the market daily.'],
                    ['come', 'आना', 'aana', 'Please come here.'],
                    ['work', 'काम करना', 'kaam karna', 'I want to work on my English every day.'],
                    ['study', 'पढ़ना', 'padhna', 'I study English every day.'],
                    ['cook', 'पकाना', 'pakaana', 'My mother cooks very well.'],
                    ['clean', 'साफ़ करना', 'saaf karna', 'I clean the house every morning.'],
                    ['wash', 'धोना', 'dhona', 'Please wash your hands.'],
                    ['sit', 'बैठना', 'baithna', 'Please sit down.'],
                    ['stand', 'खड़ा होना', 'khada hona', 'He is standing near the door.'],
                    ['walk', 'चलना', 'chalna', 'I walk to the shop.'],
                    ['run', 'दौड़ना', 'daudna', 'The children are running outside.'],
                    ['talk', 'बात करना', 'baat karna', "Let's talk for two minutes."],
                    ['listen', 'सुनना', 'sunna', 'Please listen carefully.'],
                    ['see', 'देखना', 'dekhna', 'I can see the market from here.'],
                    ['read', 'पढ़ना', 'parhna', 'I read for ten minutes daily.'],
                    ['write', 'लिखना', 'likhna', 'Please write your name here.'],
                    ['buy', 'खरीदना', 'khareedna', 'I want to buy vegetables.'],
                    ['sell', 'बेचना', 'bechna', 'He sells clothes online.'],
                    ['give', 'देना', 'dena', 'Please give me the file.'],
                    ['take', 'लेना', 'lena', 'Please take a seat.'],
                    ['make', 'बनाना', 'banaana', 'I will make tea for everyone.'],
                ],
            ],
            [
                'name' => 'Question Words & Basics',
                'entries' => [
                    ['what', 'क्या', 'kya', 'What is your name?'],
                    ['where', 'कहाँ', 'kahaan', 'Where do you live?'],
                    ['when', 'कब', 'kab', 'When do you start work?'],
                    ['who', 'कौन', 'kaun', 'Who is your teacher?'],
                    ['why', 'क्यों', 'kyon', 'Why are you late?'],
                    ['how', 'कैसे', 'kaise', 'How are you learning English?'],
                    ['how many', 'कितने', 'kitne', 'How many orders came today?'],
                    ['how much', 'कितना', 'kitna', 'How much does this cost?'],
                    ['which', 'कौन सा', 'kaun sa', 'Which file do you need?'],
                    ['whose', 'किसका', 'kiska', 'Whose phone is this?'],
                    ['yes', 'हाँ', 'haan', 'Yes, I understand.'],
                    ['no', 'नहीं', 'nahin', 'No, I am not free now.'],
                    ['and', 'और', 'aur', 'I have tea and biscuits.'],
                    ['or', 'या', 'ya', 'Tea or coffee?'],
                    ['but', 'लेकिन', 'lekin', 'I tried, but it was difficult.'],
                    ['this', 'यह', 'yeh', 'This is my notebook.'],
                    ['that', 'वह', 'voh', 'That is our house.'],
                    ['here', 'यहाँ', 'yahaan', 'Please sign here.'],
                    ['there', 'वहाँ', 'vahaan', 'The file is over there.'],
                    ['also', 'भी', 'bhi', 'I also learn new words daily.'],
                    ['only', 'सिर्फ़', 'sirf', 'It will take only five minutes.'],
                    ['very', 'बहुत', 'bahut', 'This is very important.'],
                    ['too', 'भी', 'bhi', 'I want to come too.'],
                    ['maybe', 'शायद', 'shayad', 'Maybe I will finish it today.'],
                    ['sure', 'ज़रूर', 'zaroor', 'Sure, I can help you.'],
                ],
            ],
            [
                'name' => 'Adjectives',
                'entries' => [
                    ['good', 'अच्छा', 'achha', 'This is a good idea.'],
                    ['bad', 'बुरा', 'bura', 'That was a bad experience.'],
                    ['big', 'बड़ा', 'bada', 'It is a big company.'],
                    ['small', 'छोटा', 'chhota', 'I made a small mistake.'],
                    ['new', 'नया', 'naya', 'I have a new job.'],
                    ['old', 'पुराना', 'purana', 'This is an old file.'],
                    ['hot', 'गरम', 'garam', 'The tea is very hot.'],
                    ['cold', 'ठंडा', 'thanda', 'The water is cold.'],
                    ['easy', 'आसान', 'aasaan', 'This task is easy.'],
                    ['difficult', 'मुश्किल', 'mushkil', 'Speaking was difficult at first.'],
                    ['fast', 'तेज़', 'tez', 'She types very fast.'],
                    ['slow', 'धीमा', 'dheema', 'The internet is slow today.'],
                    ['clean', 'साफ़', 'saaf', 'Keep your desk clean.'],
                    ['dirty', 'गंदा', 'ganda', 'The floor was dirty.'],
                    ['expensive', 'महँगा', 'mehanga', 'This laptop is expensive.'],
                    ['cheap', 'सस्ता', 'sasta', 'That shop is cheap.'],
                    ['beautiful', 'सुंदर', 'sundar', 'That is a beautiful dress.'],
                    ['important', 'ज़रूरी', 'zaroori', 'This email is important.'],
                    ['correct', 'सही', 'sahi', 'Your answer is correct.'],
                    ['wrong', 'गलत', 'galat', 'This number is wrong.'],
                    ['strong', 'मज़बूत', 'mazboot', 'She has a strong will.'],
                    ['weak', 'कमज़ोर', 'kamzor', 'My English was weak before.'],
                    ['heavy', 'भारी', 'bhaari', 'This box is heavy.'],
                    ['light', 'हल्का', 'halka', 'This bag is light.'],
                    ['different', 'अलग', 'alag', 'This is a different problem.'],
                ],
            ],
            [
                'name' => 'Food & Drink',
                'entries' => [
                    ['water', 'पानी', 'paani', 'Please give me some water.'],
                    ['tea', 'चाय', 'chai', 'I drink tea every morning.'],
                    ['milk', 'दूध', 'doodh', 'He drinks milk daily.'],
                    ['rice', 'चावल', 'chawal', 'We eat rice for lunch.'],
                    ['bread', 'ब्रेड', 'bread', 'I had bread for breakfast.'],
                    ['vegetable', 'सब्ज़ी', 'sabzi', 'I bought fresh vegetables.'],
                    ['fruit', 'फल', 'phal', 'Eat fruit every day.'],
                    ['sugar', 'चीनी', 'cheeni', 'Less sugar in my tea, please.'],
                    ['salt', 'नमक', 'namak', 'Add a little salt.'],
                    ['spicy', 'तीखा', 'teekha', 'This food is too spicy.'],
                    ['sweet', 'मीठा', 'meetha', 'I like sweet things.'],
                    ['breakfast', 'नाश्ता', 'naashta', 'I eat breakfast at eight.'],
                    ['lunch', 'दोपहर का खाना', 'dopahar ka khaana', 'We have lunch at one.'],
                    ['dinner', 'रात का खाना', 'raat ka khaana', 'Dinner is ready.'],
                    ['hungry', 'भूखा', 'bhookha', 'I am very hungry now.'],
                    ['thirsty', 'प्यासा', 'pyaasa', 'She looks thirsty.'],
                    ['delicious', 'स्वादिष्ट', 'svaadisht', 'This food is delicious.'],
                    ['snack', 'नाश्ता / स्नैक', 'snack', "Let's have a small snack."],
                    ['restaurant', 'रेस्टोरेंट', 'restaurant', 'We ate at a restaurant.'],
                    ['order (food)', 'ऑर्डर करना', 'order karna', "Let's order some food."],
                    ['bill', 'बिल', 'bill', 'Please bring the bill.'],
                    ['plate', 'थाली', 'thaali', 'Put it on this plate.'],
                    ['spoon', 'चम्मच', 'chammach', 'I need a spoon.'],
                    ['taste', 'स्वाद', 'svaad', 'This has a nice taste.'],
                    ['fresh', 'ताज़ा', 'taaza', 'These vegetables are fresh.'],
                ],
            ],
            [
                'name' => 'Money & Shopping',
                'entries' => [
                    ['money', 'पैसा', 'paisa', 'I need some money.'],
                    ['price', 'कीमत', 'keemat', 'What is the price of this?'],
                    ['rupee', 'रुपया', 'rupaya', 'It costs fifty rupees.'],
                    ['discount', 'छूट', 'chhoot', 'Is there any discount today?'],
                    ['bargain', 'मोल-भाव', 'mol-bhaav', 'She bargained at the market.'],
                    ['pay', 'भुगतान करना', 'bhugtaan karna', 'I will pay by card.'],
                    ['cash', 'नकद', 'nakad', 'Do you accept cash?'],
                    ['shop', 'दुकान', 'dukaan', 'There is a shop nearby.'],
                    ['market', 'बाज़ार', 'bazaar', 'I am going to the market.'],
                    ['customer', 'ग्राहक', 'grahak', 'The customer asked about the price.'],
                    ['shopkeeper', 'दुकानदार', 'dukaandaar', 'The shopkeeper was very polite.'],
                    ['bag', 'थैला', 'thaila', 'Put it in this bag.'],
                    ['size', 'साइज़', 'size', 'Do you have a bigger size?'],
                    ['colour', 'रंग', 'rang', 'I like this colour.'],
                    ['receipt', 'रसीद', 'raseed', 'Please keep the receipt.'],
                    ['change (money)', 'बाकी पैसे', 'baaki paise', 'Here is your change.'],
                    ['free', 'मुफ़्त', 'muft', 'This sample is free.'],
                    ['total', 'कुल', 'kul', 'What is the total amount?'],
                    ['online', 'ऑनलाइन', 'online', 'I ordered it online.'],
                    ['delivery', 'डिलीवरी', 'delivery', 'The delivery will come tomorrow.'],
                    ['card', 'कार्ड', 'card', 'I paid by card.'],
                    ['wallet', 'बटुआ', 'batua', 'My wallet is in my bag.'],
                    ['budget', 'बजट', 'budget', 'This is within my budget.'],
                    ['save (money)', 'बचाना', 'bachaana', 'I try to save money.'],
                    ['spend', 'खर्च करना', 'kharch karna', "Don't spend too much."],
                ],
            ],
            [
                'name' => 'Feelings & Emotions',
                'entries' => [
                    ['happy', 'खुश', 'khush', 'I am happy today.'],
                    ['sad', 'उदास', 'udaas', 'She looks sad.'],
                    ['angry', 'गुस्सा', 'gussa', 'He was angry about the delay.'],
                    ['tired', 'थका हुआ', 'thaka hua', 'I am tired after work.'],
                    ['excited', 'उत्साहित', 'utsaahit', 'I am excited for the festival.'],
                    ['nervous', 'घबराया हुआ', 'ghabraaya hua', 'I feel nervous before speaking.'],
                    ['confident', 'आत्मविश्वासी', 'aatmvishvaasi', 'I am more confident now.'],
                    ['worried', 'चिंतित', 'chintit', 'She is worried about the test.'],
                    ['comfortable', 'सहज', 'sahaj', 'I feel comfortable speaking now.'],
                    ['confused', 'उलझन में', 'uljhan mein', 'I am confused about this word.'],
                    ['proud', 'गर्वित', 'garvit', 'He is proud of his work.'],
                    ['surprised', 'हैरान', 'hairaan', 'I was surprised by the news.'],
                    ['bored', 'ऊबा हुआ', 'ooba hua', 'He looked bored in the meeting.'],
                    ['relaxed', 'आराम से', 'aaraam se', 'I feel relaxed on Sundays.'],
                    ['afraid', 'डरा हुआ', 'dara hua', "Don't be afraid to speak."],
                    ['calm', 'शांत', 'shaant', 'Stay calm during the call.'],
                    ['embarrassed', 'शर्मिंदा', 'sharminda', 'I felt embarrassed about my mistake.'],
                    ['grateful', 'आभारी', 'aabhaari', 'I am grateful for your help.'],
                    ['hopeful', 'आशावान', 'aashaavaan', 'I am hopeful about this job.'],
                    ['disappointed', 'निराश', 'niraash', 'She was disappointed with the result.'],
                    ['curious', 'जिज्ञासु', 'jigyaasu', 'I am curious to learn more.'],
                    ['satisfied', 'संतुष्ट', 'santusht', 'The customer was satisfied.'],
                    ['frustrated', 'चिढ़ा हुआ', 'chidha hua', 'He was frustrated with the delay.'],
                    ['motivated', 'प्रेरित', 'prerit', 'This program keeps me motivated.'],
                    ['pleased', 'प्रसन्न', 'prasann', 'I am pleased with my progress.'],
                ],
            ],
            [
                'name' => 'Common Verbs 2',
                'entries' => [
                    ['wear', 'पहनना', 'pehnna', 'She wears a uniform to work.'],
                    ['open', 'खोलना', 'kholna', 'Please open the door.'],
                    ['close', 'बंद करना', 'band karna', 'Please close the file.'],
                    ['start', 'शुरू करना', 'shuru karna', "Let's start the meeting."],
                    ['stop', 'रोकना', 'rokna', 'Please stop here.'],
                    ['wait', 'इंतज़ार करना', 'intezaar karna', 'Please wait a moment.'],
                    ['help', 'मदद करना', 'madad karna', 'Can you help me with this?'],
                    ['need', 'ज़रूरत होना', 'zaroorat hona', 'I need more practice.'],
                    ['want', 'चाहना', 'chaahna', 'I want to learn something new every day.'],
                    ['like', 'पसंद करना', 'pasand karna', 'I like this work.'],
                    ['love', 'प्यार करना', 'pyaar karna', 'I love learning new words.'],
                    ['hope', 'उम्मीद करना', 'ummeed karna', 'I hope to get this job.'],
                    ['think', 'सोचना', 'sochna', 'I think this is correct.'],
                    ['know', 'जानना', 'jaanna', 'I know this word now.'],
                    ['understand', 'समझना', 'samajhna', 'I understand your question.'],
                    ['remember', 'याद रखना', 'yaad rakhna', 'Please remember this word.'],
                    ['forget', 'भूलना', 'bhoolna', "Don't forget to submit the form."],
                    ['try', 'कोशिश करना', 'koshish karna', 'I will try my best.'],
                    ['finish', 'खत्म करना', 'khatam karna', 'I will finish this task today.'],
                    ['continue', 'जारी रखना', 'jaari rakhna', 'Please continue your practice.'],
                    ['find', 'ढूँढना', 'dhoondna', 'I need to find that file.'],
                    ['lose', 'खोना', 'khona', "Don't lose this receipt."],
                    ['fix', 'ठीक करना', 'theek karna', 'Can you fix this mistake?'],
                    ['change', 'बदलना', 'badalna', 'Please change the date.'],
                    ['improve', 'सुधारना', 'sudhaarna', 'I want to improve my English.'],
                ],
            ],
            [
                'name' => 'Connectors & Small Words',
                'entries' => [
                    ['because', 'क्योंकि', 'kyonki', 'I was late because of traffic.'],
                    ['so', 'इसलिए', 'isliye', 'It was raining, so I stayed home.'],
                    ['then', 'फिर', 'phir', 'First check the order, then pack it.'],
                    ['after that', 'उसके बाद', 'uske baad', 'I read the email; after that I replied.'],
                    ['before that', 'उससे पहले', 'usse pehle', 'Before that, I checked the details.'],
                    ['first', 'पहले', 'pehle', 'First, open the file.'],
                    ['next', 'अगला', 'agla', 'The next step is to save it.'],
                    ['finally', 'आख़िर में', 'aakhir mein', 'Finally, I submitted the report.'],
                    ['while', 'जब', 'jab', 'I take notes while I listen.'],
                    ['if', 'अगर', 'agar', 'If you have doubts, please ask.'],
                    ['when', 'जब', 'jab', 'Call me when you arrive.'],
                    ['until', 'जब तक', 'jab tak', 'Wait until I confirm.'],
                    ['since', 'जबसे', 'jabse', 'I have worked here since June.'],
                    ['although', 'हालाँकि', 'haalaanki', 'Although it was hard, I finished it.'],
                    ['for example', 'जैसे कि', 'jaise ki', 'For example, check the order number.'],
                    ['like (comparison)', 'जैसे', 'jaise', 'Speak like you speak Hindi — naturally.'],
                    ['instead', 'इसकी जगह', 'iski jagah', 'Use this word instead.'],
                    ['either', 'या तो', 'ya to', 'Either call or send an email.'],
                    ['both', 'दोनों', 'dono', 'Both files are ready.'],
                    ['each', 'हर एक', 'har ek', 'Check each order carefully.'],
                    ['every', 'हर', 'har', 'I practise every day.'],
                    ['another', 'एक और', 'ek aur', 'Please send another example.'],
                    ['same', 'वही', 'vahi', 'This is the same problem again.'],
                    ['extra', 'अतिरिक्त', 'atirikt', 'I need extra time for this.'],
                    ['more', 'ज़्यादा', 'zyada', 'I need more practice.'],
                ],
            ],
            [
                'name' => 'Health & Body',
                'entries' => [
                    ['health', 'स्वास्थ्य', 'swasthya', 'Health is very important.'],
                    ['body', 'शरीर', 'shareer', 'Exercise keeps the body fit.'],
                    ['head', 'सिर', 'sir', 'My head hurts a little.'],
                    ['hand', 'हाथ', 'haath', 'Wash your hands before eating.'],
                    ['leg', 'पैर', 'pair', 'He hurt his leg while running.'],
                    ['eye', 'आँख', 'aankh', 'She has beautiful eyes.'],
                    ['ear', 'कान', 'kaan', "I can't hear from this ear."],
                    ['stomach', 'पेट', 'pet', 'My stomach is upset today.'],
                    ['fever', 'बुख़ार', 'bukhaar', 'He has a mild fever.'],
                    ['cough', 'खांसी', 'khaansi', 'I have a cough since yesterday.'],
                    ['cold (illness)', 'ज़ुकाम', 'zukaam', 'She has a bad cold.'],
                    ['pain', 'दर्द', 'dard', 'I have pain in my back.'],
                    ['medicine', 'दवा', 'dawaa', 'Take this medicine after food.'],
                    ['doctor', 'डॉक्टर', 'doctor', 'I need to see a doctor.'],
                    ['clinic', 'क्लीनिक', 'clinic', 'The clinic opens at nine.'],
                    ['hospital', 'अस्पताल', 'aspataal', 'He was taken to the hospital.'],
                    ['appointment', 'अपॉइंटमेंट', 'appointment', "I have a doctor's appointment today."],
                    ['rest', 'आराम', 'aaraam', 'You need some rest.'],
                    ['exercise', 'व्यायाम', 'vyaayaam', 'I do exercise every morning.'],
                    ['healthy', 'स्वस्थ', 'swasth', 'Eat healthy food daily.'],
                    ['sick', 'बीमार', 'beemaar', 'She is feeling sick today.'],
                    ['tablet (medicine)', 'गोली', 'goli', 'Take one tablet twice a day.'],
                    ['checkup', 'जाँच', 'jaanch', 'I have a health checkup tomorrow.'],
                    ['allergy', 'एलर्जी', 'allergy', 'He has an allergy to dust.'],
                    ['energy', 'ऊर्जा', 'oorja', 'I feel full of energy today.'],
                ],
            ],
            [
                'name' => 'Technology & Phone',
                'entries' => [
                    ['mobile phone', 'मोबाइल फ़ोन', 'mobile phone', 'My mobile phone battery is low.'],
                    ['app', 'ऐप', 'app', 'I downloaded a new app.'],
                    ['wifi', 'वाईफ़ाई', 'wifi', 'The wifi is not working.'],
                    ['network', 'नेटवर्क', 'network', 'There is no network here.'],
                    ['battery', 'बैटरी', 'battery', 'Please charge your battery.'],
                    ['charger', 'चार्जर', 'charger', 'Can I borrow your charger?'],
                    ['message (text)', 'मैसेज', 'message', 'I will send you a message.'],
                    ['call', 'कॉल', 'call', 'Give me a call in the evening.'],
                    ['missed call', 'मिस्ड कॉल', 'missed call', 'You have a missed call.'],
                    ['video call', 'वीडियो कॉल', 'video call', "Let's do a video call tonight."],
                    ['screenshot', 'स्क्रीनशॉट', 'screenshot', 'Send me a screenshot of that.'],
                    ['social media', 'सोशल मीडिया', 'social media', 'She spends time on social media.'],
                    ['photo', 'फ़ोटो', 'photo', 'Take a nice photo here.'],
                    ['contact', 'कॉन्टैक्ट', 'contact', 'Save this number as a contact.'],
                    ['settings', 'सेटिंग्स', 'settings', "Go to your phone's settings."],
                    ['update (app)', 'अपडेट करना', 'update karna', 'Please update this app.'],
                    ['install', 'इंस्टॉल करना', 'install karna', 'Install this app first.'],
                    ['lock (phone)', 'लॉक करना', 'lock karna', 'Always lock your phone.'],
                    ['volume', 'आवाज़', 'aawaaz', 'Turn down the volume, please.'],
                    ['storage', 'स्टोरेज', 'storage', 'My phone storage is full.'],
                    ['link', 'लिंक', 'link', 'Click on this link.'],
                    ['search (internet)', 'सर्च करना', 'search karna', 'Search for it online.'],
                    ['website', 'वेबसाइट', 'website', 'Check the website for details.'],
                    ['notification', 'नोटिफ़िकेशन', 'notification', 'I got a notification just now.'],
                    ['online account', 'ऑनलाइन अकाउंट', 'online account', 'Create a free online account first.'],
                ],
            ],
            [
                'name' => 'Weather & Seasons',
                'entries' => [
                    ['weather', 'मौसम', 'mausam', 'The weather is nice today.'],
                    ['hot (weather)', 'गरम', 'garam', 'It is very hot outside.'],
                    ['cold (weather)', 'ठंडा', 'thanda', 'It gets cold in December.'],
                    ['rain', 'बारिश', 'baarish', 'It is raining heavily.'],
                    ['sun', 'धूप', 'dhoop', 'There is bright sun today.'],
                    ['cloud', 'बादल', 'baadal', 'The sky is full of clouds.'],
                    ['wind', 'हवा', 'hawa', 'There is strong wind today.'],
                    ['summer', 'गर्मी', 'garmi', 'Summer is very hot here.'],
                    ['winter', 'सर्दी', 'sardi', 'I like winter mornings.'],
                    ['monsoon', 'मानसून', 'monsoon', 'Monsoon starts in July.'],
                    ['humid', 'उमस भरा', 'umas bhara', 'It feels humid today.'],
                    ['temperature', 'तापमान', 'taapmaan', "Check today's temperature."],
                    ['umbrella', 'छाता', 'chhata', 'Take an umbrella with you.'],
                    ['flood', 'बाढ़', 'baadh', 'There was a flood last year.'],
                    ['storm', 'तूफ़ान', 'toofaan', 'A storm is expected tonight.'],
                    ['sunny', 'धूप वाला', 'dhoop waala', "It's a sunny day."],
                    ['cloudy', 'बादल छाए हुए', 'baadal chhaaye hue', 'It looks cloudy today.'],
                    ['season', 'मौसम', 'mausam', 'Which season do you like?'],
                    ['dry', 'सूखा', 'sookha', 'The weather is very dry.'],
                    ['wet', 'गीला', 'geela', 'The ground is wet after rain.'],
                    ['fog', 'कोहरा', 'kohra', 'There is fog this morning.'],
                    ['climate', 'जलवायु', 'jalvaayu', 'The climate here is pleasant.'],
                    ['forecast (weather)', 'मौसम का पूर्वानुमान', 'mausam ka poorvaanumaan', 'Check the weather forecast.'],
                    ['degree (temperature)', 'डिग्री', 'degree', 'It is thirty degrees today.'],
                    ['pleasant', 'सुहावना', 'suhaavna', 'The weather is pleasant today.'],
                ],
            ],
            [
                'name' => 'Making Plans & Invitations',
                'entries' => [
                    ['plan (noun)', 'योजना', 'yojana', 'What is your plan for today?'],
                    ['invite', 'आमंत्रित करना', 'aamantrit karna', 'I want to invite you home.'],
                    ['invitation', 'निमंत्रण', 'nimantran', 'Thank you for the invitation.'],
                    ['free (available)', 'खाली', 'khaali', 'Are you free this evening?'],
                    ['busy', 'व्यस्त', 'vyast', 'I am busy right now.'],
                    ['meet up', 'मिलना', 'milna', "Let's meet up this weekend."],
                    ['join', 'शामिल होना', 'shaamil hona', 'Will you join us for dinner?'],
                    ['celebrate', 'जश्न मनाना', 'jashn manaana', 'We will celebrate together.'],
                    ['party', 'पार्टी', 'party', 'There is a party on Sunday.'],
                    ['host', 'मेज़बान', 'mezbaan', 'She is a wonderful host.'],
                    ['accept (invitation)', 'स्वीकार करना', 'sveekaar karna', 'I happily accept your invitation.'],
                    ['decline (politely)', 'मना करना', 'mana karna', 'I have to decline this time.'],
                    ['agree', 'सहमत होना', 'sehmat hona', "I agree, let's do it."],
                    ['disagree', 'असहमत होना', 'asehmat hona', 'I disagree, I prefer another day.'],
                    ['suggestion', 'सुझाव', 'sujhaav', 'I have a suggestion for the trip.'],
                    ['opinion', 'राय', 'raay', 'What is your opinion about this place?'],
                    ['decide', 'फ़ैसला करना', 'faisla karna', "Let's decide the time together."],
                    ['postpone', 'स्थगित करना', 'sthagit karna', 'Can we postpone it to Sunday?'],
                    ['reschedule', 'समय बदलना', 'samay badalna', "Let's reschedule our plan."],
                    ['remind', 'याद दिलाना', 'yaad dilaana', 'Please remind me about the plan.'],
                    ['confirm', 'पुष्टि करना', 'pushti karna', 'Please confirm by tomorrow.'],
                    ['get together', 'इकट्ठा होना', 'ikattha hona', 'The whole family got together.'],
                    ['occasion', 'अवसर', 'avsar', "It's a special occasion today."],
                    ['surprise', 'सरप्राइज़', 'surprise', 'We planned a surprise for her.'],
                    ['catch up', 'बातें करना', 'baaten karna', "Let's catch up over tea."],
                ],
            ],
            [
                'name' => 'Travel & Commute',
                'entries' => [
                    ['travel', 'यात्रा', 'yatra', 'I travel by bus to work.'],
                    ['bus', 'बस', 'bus', 'The bus is late today.'],
                    ['train', 'ट्रेन', 'train', 'I take the train to the city.'],
                    ['auto/rickshaw', 'ऑटो', 'auto', 'I took an auto to the market.'],
                    ['station', 'स्टेशन', 'station', 'Meet me at the station.'],
                    ['ticket', 'टिकट', 'ticket', 'I bought a bus ticket.'],
                    ['route', 'रास्ता', 'raasta', 'Which route do you take?'],
                    ['traffic', 'ट्रैफ़िक', 'traffic', 'There was heavy traffic today.'],
                    ['distance', 'दूरी', 'dooree', 'The distance is not too far.'],
                    ['near', 'पास', 'paas', 'The market is near my house.'],
                    ['far', 'दूर', 'door', 'The market is a bit far.'],
                    ['direction', 'दिशा', 'disha', 'Can you give me directions?'],
                    ['left', 'बाएँ', 'baayen', 'Turn left at the signal.'],
                    ['right', 'दाएँ', 'daayen', 'The bank is on the right.'],
                    ['straight', 'सीधे', 'seedhe', 'Go straight, then turn.'],
                    ['arrive', 'पहुँचना', 'pahunchna', 'I arrive at nine every day.'],
                    ['leave (depart)', 'निकलना', 'nikalna', 'I leave home at eight.'],
                    ['delay', 'देरी', 'deri', 'There is a slight delay.'],
                    ['on time', 'समय पर', 'samay par', 'Please come on time.'],
                    ['fare', 'किराया', 'kiraaya', 'What is the auto fare?'],
                    ['pick up', 'लेने जाना', 'lene jaana', 'He will pick me up at six.'],
                    ['drop', 'छोड़ना', 'chhodna', 'Please drop me at the market.'],
                    ['parking', 'पार्किंग', 'parking', 'The parking is behind the building.'],
                    ['helmet', 'हेलमेट', 'helmet', 'Always wear a helmet.'],
                    ['commute', 'आना-जाना', 'aana-jaana', 'My commute takes thirty minutes.'],
                ],
            ],
            [
                'name' => 'Home & Household',
                'entries' => [
                    ['house', 'घर', 'ghar', 'This is my house.'],
                    ['rent', 'किराया', 'kiraaya', 'The rent is due this week.'],
                    ['landlord', 'मकान मालिक', 'makaan maalik', 'Our landlord lives nearby.'],
                    ['repair', 'मरम्मत', 'marammat', 'The tap needs repair.'],
                    ['electricity', 'बिजली', 'bijli', 'The electricity went off again.'],
                    ['water supply', 'पानी की सप्लाई', 'paani ki supply', 'Water supply comes in the morning.'],
                    ['bill (household)', 'बिल', 'bill', 'Please pay the electricity bill.'],
                    ['furniture', 'फ़र्नीचर', 'furniture', 'We bought new furniture.'],
                    ['kitchen', 'रसोई', 'rasoi', 'She is cooking in the kitchen.'],
                    ['bedroom', 'बेडरूम', 'bedroom', 'The bedroom is upstairs.'],
                    ['bathroom', 'बाथरूम', 'bathroom', 'The bathroom tap is leaking.'],
                    ['broom', 'झाड़ू', 'jhaadu', 'Bring the broom, please.'],
                    ['tap', 'नल', 'nal', 'Turn off the tap.'],
                    ['leak', 'रिसाव', 'leak', 'There is a small leak in the pipe.'],
                    ['switch', 'स्विच', 'switch', 'Turn on the light switch.'],
                    ['fan', 'पंखा', 'pankha', 'Please switch on the fan.'],
                    ['gas', 'गैस', 'gas', 'We need a new gas cylinder.'],
                    ['garbage', 'कचरा', 'kachra', 'Please take out the garbage.'],
                    ['neighbourhood', 'मोहल्ला', 'mohalla', 'Our neighbourhood is quiet.'],
                    ['society (residential)', 'सोसाइटी', 'society', 'Our society has a small park.'],
                    ['maintenance', 'रखरखाव', 'rakh-rakhaav', 'Maintenance charges are due.'],
                    ['guard (security)', 'गार्ड', 'guard', 'Ask the guard for help.'],
                    ['move (house)', 'शिफ़्ट होना', 'shift hona', 'We are moving to a new house.'],
                    ['borrow', 'उधार लेना', 'udhaar lena', 'Can I borrow your ladder?'],
                    ['lend', 'उधार देना', 'udhaar dena', 'He lent me his umbrella.'],
                ],
            ],
            [
                'name' => 'Common Verbs 3',
                'entries' => [
                    ['explain', 'समझाना', 'samjhaana', 'Let me explain what happened.'],
                    ['describe', 'वर्णन करना', 'varnan karna', 'Can you describe the problem?'],
                    ['handle', 'संभालना', 'sambhaalna', 'I can handle this myself.'],
                    ['manage', 'प्रबंधित करना', 'prabandhit karna', 'She manages her time well.'],
                    ['organize', 'व्यवस्थित करना', 'vyavasthit karna', 'I organize my cupboard every month.'],
                    ['arrange', 'व्यवस्था करना', 'vyavastha karna', 'Please arrange the chairs.'],
                    ['deliver', 'पहुँचाना', 'pahunchaana', 'He delivered the parcel himself.'],
                    ['collect', 'इकट्ठा करना', 'ikattha karna', 'Please collect your things.'],
                    ['provide', 'प्रदान करना', 'pradaan karna', 'They provide free water here.'],
                    ['support', 'सहायता करना', 'sahaayata karna', 'My family supports me a lot.'],
                    ['solve', 'हल करना', 'hal karna', "Let's solve this problem together."],
                    ['inform', 'सूचित करना', 'soochit karna', "Please inform me if you're late."],
                    ['respond', 'जवाब देना', 'jawaab dena', 'She responded very kindly.'],
                    ['ensure', 'सुनिश्चित करना', 'sunishchit karna', 'Please ensure the door is locked.'],
                    ['achieve', 'हासिल करना', 'haasil karna', 'I achieved my goal this year.'],
                    ['review', 'समीक्षा करना', 'samiksha karna', "Let's review our plan."],
                    ['monitor', 'निगरानी करना', 'nigraani karna', 'I monitor my daily progress.'],
                    ['negotiate', 'बातचीत करना', 'baatcheet karna', 'We negotiated a fair price.'],
                    ['recommend', 'सिफ़ारिश करना', 'sifaarish karna', 'I recommend this doctor.'],
                    ['celebrate', 'जश्न मनाना', 'jashn manaana', 'We celebrate every festival with our neighbours.'],
                    ['apologize', 'माफ़ी माँगना', 'maafi maangna', 'I apologized for my mistake.'],
                    ['forgive', 'माफ़ करना', 'maaf karna', 'Please forgive me.'],
                    ['share', 'साझा करना', 'saanjha karna', 'Please share your food.'],
                    ['thank', 'धन्यवाद देना', 'dhanyavaad dena', 'I want to thank you for your help.'],
                    ['trust', 'भरोसा करना', 'bharosa karna', 'I trust you completely.'],
                ],
            ],
            [
                'name' => 'Confidence & Social Words',
                'entries' => [
                    ['introduce (oneself)', 'अपना परिचय देना', 'apna parichay dena', 'Let me introduce myself.'],
                    ['compare', 'तुलना करना', 'tulna karna', "Let's compare the two options."],
                    ['prefer', 'पसंद करना', 'pasand karna', 'I prefer tea over coffee.'],
                    ['point of view', 'नज़रिया', 'nazariya', "That's an interesting point of view."],
                    ['experience', 'अनुभव', 'anubhav', 'That was a wonderful experience.'],
                    ['achievement', 'उपलब्धि', 'upalabdhi', 'Finishing the course was a big achievement.'],
                    ['goal', 'लक्ष्य', 'lakshya', 'My goal is to speak fluently.'],
                    ['background', 'पृष्ठभूमि', 'prishthbhoomi', 'Tell me about your background.'],
                    ['hobby', 'शौक़', 'shauk', 'Reading is my hobby.'],
                    ['interest', 'रुचि', 'ruchi', 'I have an interest in music.'],
                    ['honest', 'ईमानदार', 'imaandaar', 'He is a very honest person.'],
                    ['respect', 'सम्मान', 'sammaan', 'I respect your opinion.'],
                    ['appreciate', 'सराहना करना', 'saraahna karna', 'I really appreciate your help.'],
                    ['congratulate', 'बधाई देना', 'badhai dena', 'Let me congratulate you.'],
                    ['encourage', 'प्रोत्साहित करना', 'protsaahit karna', 'She always encourages me.'],
                    ['brave', 'बहादुर', 'bahadur', 'Be brave and speak up.'],
                    ['patient (adj)', 'धैर्यवान', 'dhairyavaan', 'Be patient, it takes time.'],
                    ['sincere', 'सच्चा', 'sachcha', 'She is sincere and kind.'],
                    ['generous', 'उदार', 'udaar', 'He is very generous with his time.'],
                    ['cheerful', 'ख़ुशमिज़ाज', 'khushmizaaj', 'She is always cheerful.'],
                    ['optimistic', 'आशावादी', 'aashaavaadi', 'Try to stay optimistic.'],
                    ['determined', 'दृढ़ निश्चयी', 'dridh nishchayi', 'She is determined to learn English.'],
                    ['independent', 'स्वतंत्र', 'swatantra', 'I want to be independent.'],
                    ['responsible', 'ज़िम्मेदार', 'zimmedaar', 'He is a responsible person.'],
                    ['genuine', 'सच्चा', 'sachcha', 'That was a genuine compliment.'],
                ],
            ],
        ];
    }
}
